### ISSUE TITLE
`insert/part` does not work with negative `length`

### ISSUE THREAD

**Issue by Oldes** [red/red#5060] opened 2022-02-01 09:52 UTC
Currently:
```red
a: make block! 0
b: at [1 2 3 4 5 6 7 8 9] 5
insert/part a b -2
a ;== [5 6 7 8 9] ;<---- it should be [3 4], like in Rebol!
```

**Comment by hiiamboris** [comment] 2022-02-01 10:01
dupe of https://github.com/red/red/issues/4106

**Closed** 2022-02-01 12:07 UTC
Labels: status.duplicate
