### ISSUE TITLE
Rich-text "auto-centers" when over a background with alpha channel

### ISSUE THREAD

**Issue by luce80** [red/red#5214] opened 2022-09-21 18:01 UTC
**Describe the bug**
When a transparent background is specified the rich-text is "automatically" centered

**To reproduce**
```
view [rich-text "Message to display" 255.255.255.255]
```
**Expected behavior**
The text should be left-aligned as that is default alignment as shown when no color or no-alpha channel is specified
```
view [rich-text "Message to display" 255.255.255]
```
**Screenshots**
https://files.gitter.im/55b1d8290fc9f982beaacceb/br1X/image.png

**Platform version**
```
>> about
Red 0.6.4 for Windows built 18-Sep-2022/3:17:02+02:00  commit #5035ab9
```

**Comment by qtxie** [comment] 2022-09-21 21:04
Why not make it center by default? It's centered in `base` face.

If we all agree that left-aligned should be the default, I'll do the change.

**Comment by hiiamboris** [comment] 2022-09-21 21:48
I'm for consistency. But I think left alignment default comes from use of rich-text faces inside `draw`, where it makes sense.

**Comment by greggirwin** [comment] 2022-09-21 22:54
For now I would have transparent behavior match non-transparent behavior. It's paragraph oriented, which implies left alignment in general (ignoring right-to-left G18N issues).

Boris' research and comments are important, but I don't think now is the time to redesign it. When we do, let's come at it with clear use cases, and decide which fall inside and outside the eventual target scope. e.g. rich text to build a Red browser is great, document oriented, and needs to support inline links. The wild and wooly things `spaces` can do drags it toward a wormhole. I suspect there's a point of no return in the design where really advanced things fall out of scope, and a higher level elides elements as they become too small to be useful, etc.

**Comment by luce80** [comment] 2022-09-22 18:06
In the same episode:
```
view [rich-text "⚠️" font-size 40 glass]
```
![image](https://user-images.githubusercontent.com/17967405/191819654-c2ec6ab3-4ace-4487-90ce-713a59b35b24.png)
```
view [rich-text "⚠️" font-size 40]
```
![image](https://user-images.githubusercontent.com/17967405/191819871-e2b7c59f-0f2c-40a1-8bdf-40b9db8ae711.png)

**Comment by hiiamboris** [comment] 2022-09-22 18:22
That looks like with transparency it's not a D2D but GDI face.

**Comment by qtxie** [comment] 2022-09-22 21:35
It's a known issue. When using `face/text` only without `face/draw`, we use GDI+ to draw on the DC. That is no heavy D2D objects need to be created. It's an optimization (seems to be a premature one 😅 ). So it should be quite efficient to create _a lot of_ transparent faces to show the text. That's mainly used for writing our own `text` face to replace the native one.

I think we can change it to use D2D to see if the overhead really causes some issues in real-world code.

**Comment by hiiamboris** [comment] 2022-09-23 07:17
If it's called `rich-text` it should be one ;)

**Comment by qtxie** [comment] 2022-09-23 09:04
Well. The current way gives more options to the user. If you want to draw colored emoji, use `draw`. While if you just want simple text like `text` face (also use less resources and faster), use `face/text`.

**Comment by hiiamboris** [comment] 2022-09-23 09:39
For simple text we have a `base` face. Which I suppose is the same currently as `rich-text` :)

**Comment by greggirwin** [comment] 2022-09-23 16:48
I'll say again:

> let's come at it with clear use cases,

- Browser with embedded links (@toomasv did this simply, and nicely for help in DiaGrammar, though it still needs cursor changes on mouse-over testing)
- Syntax highlighting in consoles, editors, and other tooling like terminals
- Presentation software
- Reporting/Dashboards
- Tables/Spreadsheets
- Word Processor/WYSIWYG editor
- Markdown rendering
- Rich email/messaging/chat
- UI popups
- ...

Inline vs block elements is one distinction, but how content is created and maintained and how the code is structured to deal with it are others.

**Comment by hiiamboris** [comment] 2022-09-23 17:03
How is this even related to whether rich-text face centers it's /text facet or not?

**Comment by luce80** [comment] 2022-09-23 17:54
The default text alignment is not the main problem. My last two examples shows that:
I can not rely on a default `rich-text` alignment because it varies when alpha channel is specified
I can not rely on colored `rich-text` emojis (preferable) because it varies when alpha channel is specified
I can not rely on right `rich-text` emojis because a "strange rectangle" could appear when alpha channel is specified

Should I really write:
```
ft: make font! [size: 40]
view [base 150x150 glass draw [font ft text 0x0 "⚠️"]]
```
instead ?
I can live with that but should be documented and perhaps an error "do not use rich-text or emojis with alpha channel" should appear.

**Comment by greggirwin** [comment] 2022-09-23 18:20
> How is this even related to whether rich-text face centers it's /text facet or not by default?

How it behaves depends on how we expect to use it. Or when to use `base` vs `draw` vs `rich-text`.

**Comment by hiiamboris** [comment] 2022-09-23 18:22
@greggirwin I think everything you mentioned should be using `draw`.

**Comment by greggirwin** [comment] 2022-09-23 18:29
If @dockimbel and @qtxie agree with you, with my guess being that rich popups have little value if they contain only rich text, then we can pretty much drop `rich-text`. My feeling is that using `draw` for most of those scenarios means you'll simply end up reinventing `rich-text`.

**Comment by hiiamboris** [comment] 2022-09-23 18:40
We can't drop it because it's used by `draw` currently. Besides I think the main point of having `rich-text` in VID is simply to automate it's `/data` processing by `rtd-layout`. Which is even stronger point that `box` serves (just color override).

**Comment by qtxie** [comment] 2022-09-23 23:46
The `rich-text` in `draw` is a graphic object, like text, image, even it uses the same object layout as face!. They are two different objects. like image! and image face.

We can add more features to `rich-text face`, for example, edit mode, scrolling. like an area face but with rich text format support.

**Comment by qtxie** [comment] 2022-09-24 04:17
Looks like there is a bug in string!. The length should be 1.
```
>> length? "⚠️"
== 2
```

**Comment by qtxie** [comment] 2022-09-24 07:15
> In the same episode:
> 
> ```
> view [rich-text "⚠️" font-size 40 glass]
> ```
> 
> ![image](https://user-images.githubusercontent.com/17967405/191819654-c2ec6ab3-4ace-4487-90ce-713a59b35b24.png)
> 
> ```
> view [rich-text "⚠️" font-size 40]
> ```
> 
> ![image](https://user-images.githubusercontent.com/17967405/191819871-e2b7c59f-0f2c-40a1-8bdf-40b9db8ae711.png)

@luce80 Your text contains a `VARIATION SELECTOR-16` (UTF-8: EFB88F) char. https://www.fileformat.info/info/unicode/char/fe0f/index.htm

```
>> to-binary "⚠️"
== #{E29AA0EFB88F}
>> to-binary #"⚠"
== #{E29AA0}
```

**Closed** 2022-09-24 07:40 UTC
Labels: status.built, status.tested, GUI

**Comment by qtxie** [comment] 2022-09-24 08:04
@hiiamboris Two tests failed due to this change. Would you please update the tests?
```
~~~started test~~~ base-self-test
===group=== color rendering check
--test-- crc-11 - base, preset colors bgnd alpha FAILED**************
--test-- crc-11 - base, preset colors both alpha FAILED**************
```

**Comment by hiiamboris** [comment] 2022-09-24 08:06
But I'm testing `base` not `rich-text`

**Comment by qtxie** [comment] 2022-09-24 08:11
@hiiamboris They use the same code path for drawing.

**Comment by hiiamboris** [comment] 2022-09-24 08:17
Funny I have only one test failing, `--test-- tic-5 to-image of an image font alpha FAILED**************`

**Comment by hiiamboris** [comment] 2022-09-24 08:36
Nevermind @qtxie, false alarms, I can't reproduce those failures even `tic-5`.

**Comment by qtxie** [comment] 2022-09-24 21:28
@hiiamboris Good! Thanks for checking it.
