### ISSUE TITLE
bug in _to_ word

### ISSUE THREAD

**Issue by GerardSontag** [red/red#1921] opened 2016-05-20 08:46 UTC
red>> to number! "10"

Exit the red console without any error message

**Comment by nc-x** [comment] 2016-05-20 10:47
@GerardSontag `to` is not completely implemented yet. It is a "todo".

**Comment by GerardSontag** [comment] 2016-05-20 11:58
Ok.

**Comment by dockimbel** [comment] 2016-05-20 12:11
Duplicate of #1613.

**Closed** 2016-05-20 12:11 UTC
Labels: status.duplicate
