### ISSUE TITLE
inconsistency in creating image! values

### ISSUE THREAD

**Issue by meijeru** [red/red#2883] opened 2017-07-12 08:47 UTC
Since the fix for #2857 the ARGB components of an `image!` value can not only be set to a `binary!` value, but also to a `tuple!` value (it is used for  all pixels) and to an `integer!` value (its 4 bytes are used as a tuple). The latter facility is not available when doing a `make image!`

**Comment by hiiamboris** [comment] 2019-09-23 14:39
I believe this may be closed as it's consistent now.
See https://github.com/red/red/pull/3608
`make image! [2x2 99.66.33]` works, while `img/1: 100` (integer assignment) was never by design and so is rightfully complained about after `make image! [2x2 100]`.

**Closed** 2019-09-23 20:50 UTC
