### ISSUE TITLE
VIEW Camera: Access Violation in Red --cli and error bug in GUI Console

### ISSUE THREAD

**Issue by gltewalt** [red/red#3349] opened 2018-04-25 18:28 UTC
### Expected behavior
Expect an error message with an invalid selection.
`view [camera select 0]`
`This device cannot preview!`
### Actual behavior
In Red --cli
```
*** Runtime Error 1: access violation
*** at: 772822E2h
``` 

In GUI Console:
Window loses focus and the following output is returned.
```
>> view [camera select 1]
This device cannot preview!
This device cannot preview!
```

### Steps to reproduce the problem
Make an invalid selection with `view [camera select <your-selection-number>]`
### Red and platform version
```
-----------RED & PLATFORM VERSION----------- 
RED: [ branch: "master" tag: #v0.6.3 ahead: 657 date: 25-Apr-2018/2:03:29 commit: #e80f0759eaef05e18d65426cf25b7e5727a6737e ]
PLATFORM: [ name: "Windows 7" OS: 'Windows arch: 'x86-64 version: 6.1.0 build: 7601 ]
--------------------------------------------
```

**Comment by gltewalt** [comment] 2018-04-26 20:18
Fixed except for GUI Console loses focus after:
```
*** Access Error: cannot open: 0
*** Where: make-view
*** Stack: view show show  
```

**Comment by gltewalt** [comment] 2018-12-24 06:36
GUI Console still loses focus even though it doesn't look like it does. 
The GUI Console must be clicked on for it to respond to any keyboard input. After clicking in the window, it works as it should.

**Comment by hiiamboris** [comment] 2020-03-12 15:39
Dupe of https://github.com/red/red/issues/3288

**Closed** 2022-09-13 16:49 UTC
Labels: status.built, type.bug, GUI
