### ISSUE TITLE
set-path!s execute get-word!s

### ISSUE THREAD

**Issue by WiseGenius** [red/red#2297] opened 2016-11-03 10:26 UTC
```
red>> m: copy #()
== #()
red>> o: make object! [w: none]
== make object! [
    w: none
]
red>> f: function [x][loop 20 [prin uppercase x] print x]
== func [x][loop 20 [prin uppercase x] print x]
red>> 
red>> 
red>> v: :f "a"					;;<- This behaves as expected.
== "a"
red>> 
red>> 
red>> m/k: :f "a"				;;<- This unexpectedly executes the function.
AAAAAAAAAAAAAAAAAAAAA
== func [x][loop 20 [prin uppercase x] print x]
red>> 
red>> 
red>> o/w: :f "a"				;;<- This unexpectedly executes the function.
AAAAAAAAAAAAAAAAAAAAA
== func [x][loop 20 [prin uppercase x] print x]
```

May be related to [#2201](https://github.com/red/red/issues/2201).

**Comment by WiseGenius** [comment] 2016-11-03 10:33
Looks like it's not just `get-word!`s.
```
red>> m: copy #()
== #()
red>> m/k: function [x][loop 20 [prin uppercase x] print x] "a"
AAAAAAAAAAAAAAAAAAAAA
== func [x][loop 20 [prin uppercase x] print x]
```

**Comment by WiseGenius** [comment] 2016-11-03 11:14
Looks like it isn't just `set-path!`s either:
```
red>> m: copy #()
== #()
red>> set 'm/k function [x][loop 20 [prin uppercase x] print x] "a"
*** Script Error: m/k is missing its x argument
*** Where: k
```

It's just the additional execution that's the problem. In all the examples so far, the assignment does succeed:
```
red>> m
== #(
    k: func [x][loop 20 [prin uppercase x] print x]
)
```

**Comment by dockimbel** [comment] 2016-11-03 16:13
This seems to be a duplicate of, or related to: #1993 and #2138.

**Closed** 2017-03-01 17:28 UTC
Labels: status.built, status.tested, type.bug
