### ISSUE TITLE
Crash on pair / float

### ISSUE THREAD

**Issue by mikeparr** [red/red#1673] opened 2016-03-03 10:07 UTC
Using red-054  Windows 7.  Code:

print 100x20 / 3.2
*** Math Error: unsupported right operand for pair operation
*** Runtime Error 13: integer divide by zero

*** at: 0042D454h
------------------------------------------
Red  indicates an error in the right operand, but then produces 'divide by zero' error, and crashes.

**Comment by dockimbel** [comment] 2016-03-03 10:23
I get proper error catching in latest Red version from master branch:
```
red>> print 100x20 / 3.2
*** Script error: float type is not allowed here
*** Where: /
```

**Comment by dockimbel** [comment] 2016-03-16 08:09
Can't reproduce this issue with Red versions from master branch, so I'm closing it.

**Closed** 2016-03-16 08:10 UTC
Labels: status.dismissed, status.resolved
