### ISSUE TITLE
Access violation when calling `help` after `recycle`

### ISSUE THREAD

**Issue by dander** [red/red#3549] opened 2018-10-02 06:48 UTC
### Expected behavior
no access violation
### Actual behavior
Both GUI and console crash with the help call, though it doesn't always happen the first time.
### Steps to reproduce the problem
```
>> recycle loop 3 [? recycle]
USAGE:
     RECYCLE

DESCRIPTION:
     RECYCLE is a native! value.

REFINEMENTS:
     /on          =>
     /off         =>

USAGE:
     RECYCLE

DESCRIPTION:
     RECYCLE is a native! value.

REFINEMENTS:
     /on          =>
     /off         =>


*** Runtime Error 1: access violation
*** at: 00429DEAh
```
### Red and platform version
```
-----------RED & PLATFORM VERSION-----------
RED: [ branch: "master" tag: #v0.6.3 ahead: 1060 date: 2-Oct-2018/3:13:15 commit: #bceaf7c09b7c61a8a2bc77a4669ab91ef4058dd3 ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 17134 ]
--------------------------------------------
```

**Comment by dockimbel** [comment] 2018-10-06 01:07
Cannot reproduce on latest version from master branch. Please confirm that the issue is gone.

**Comment by 9214** [comment] 2018-10-06 04:39
@dockimbel 

```
>> about
Red 0.6.3 for Windows built 6-Oct-2018/7:28:28+05:00 commit #dafc828

>> recycle ? recycle ; 3 times

*** Runtime Error 1: access violation
*** at: 00429DEAh
```

**Comment by dander** [comment] 2018-10-06 05:57
I can also still reproduce with the latest automated build (same commit hash mentioned by @9214).

**Comment by endo64** [comment] 2018-10-06 14:55
Same error with latest build on master.

```
--== Red 0.6.3 ==--
Type HELP for starting information.

>> recycle ? recycle

*** Runtime Error 1: access violation
*** at: 00429DEAh
```

If I type `about` before `recycle ? recycle` then it crashes on fifth try, otherwise crashes on first try.

`Red 0.6.3 for Windows built 3-Oct-2018/23:33:58+03:00 commit #f4d090b`

**Comment by qtxie** [comment] 2018-10-07 01:54
@dander I pushed a fix. Please check if the issue is gone.

**Comment by dander** [comment] 2018-10-07 03:04
I can no longer reproduce with the latest build 👍

**Closed** 2018-10-09 22:33 UTC
Labels: status.built, status.tested, type.bug
