### ISSUE TITLE
Difference in how compiler and interpreter evaluate replace/case/all quote :a/b/A/a/B [a] 'x

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#3624] opened 2018-12-01 01:38 UTC
**Describe the bug**
Difference in how compiler and interpreter evaluate replace/case/all quote :a/b/A/a/B [a] 'x
```text
replace/case/all quote :a/b/A/a/B [a] 'x - compiled
::a/b/A/x/B

replace/case/all quote :a/b/A/a/B [a] 'x - interpreted
:x/b/A/x/B
```

**To Reproduce**
Run this code:

```
Red[]

print "replace/case/all quote :a/b/A/a/B [a] 'x - compiled"
probe replace/case/all quote :a/b/A/a/B [a] 'x
print ""
print "replace/case/all quote :a/b/A/a/B [a] 'x - interpreted"
probe do [ replace/case/all quote :a/b/A/a/B [a] 'x ]
``` 

**Expected behavior**

**Platform version(please complete the following information):**
commit 1e0d5ec2360b336ef8111546e3221024dc28e31f (HEAD -> master, upstream/master)

**Comment by hiiamboris** [comment] 2019-11-23 21:24
Not `replace`'s fault:

`quote :a/b/A/a/B` >>
```
:a/b/A/a/B   ;) interpreted
::a/b/A/a/B  ;) compiled
```

**Comment by 9214** [comment] 2020-07-30 17:43
Turns out https://github.com/red/red/issues/4451 was a dupe of this one.

**Closed** 2020-09-25 09:01 UTC
Labels: type.bug
