### ISSUE TITLE
Fix for #1920 breaks Red

### ISSUE THREAD

**Issue by Zamlox** [red/red#1942] opened 2016-05-27 21:57 UTC
Following code will crash Red:
```
w: layout/only [base 100x100 blue]
main: layout [base 200x200 30.40.50.255]
main/pane/1/pane: w
view main
```

Because 'main' has alpha? set, ```Os-make-view``` will call ```process-layered-region``` which calls ```get-face-handle```. Last function called will check for ```state``` and it will crash.

**Comment by qtxie** [comment] 2016-05-27 22:45
@Zamlox Thanks. I knew I forgot something... 囧

**Comment by qtxie** [comment] 2016-05-27 23:02
Should be fixed with commit: 692ad4746116eb63062bce122d1e88b5fbbb7ea6

**Comment by nc-x** [comment] 2016-05-28 03:23
@qtxie 
![untitled](https://cloud.githubusercontent.com/assets/16458742/15624841/7de7ab0e-24b1-11e6-9ab1-ea44778cef7b.png)
This is #1942

**Comment by dockimbel** [comment] 2016-05-31 14:02
@qtxie @nc-x So is #1942 fixed? I can't reproduce the crash anymore.

**Comment by qtxie** [comment] 2016-05-31 14:05
Should be fixed now.

**Comment by nc-x** [comment] 2016-06-01 03:32
@dockimbel I never got any crashes. 
I just redownloaded the source after the commit which fixed #1920 and caused this issue but got no crashes. :smile: 
And I am not getting any crashes after the fix for this as well. :smile:
So most probably fixed.

**Comment by dockimbel** [comment] 2016-06-01 06:40
Shoudn't we see a blue face inside the window? It doesn't seem to work, so maybe we should close this ticket and open a new one for that other issue? @qtxie What do you think?

**Comment by qtxie** [comment] 2016-06-01 06:51
Nope. We can not see anything because the `main` is totally transparent.

**Comment by dockimbel** [comment] 2016-06-01 07:08
But the `main` face has a child face which is blue (not transparent), we should see it?

**Comment by qtxie** [comment] 2016-06-01 07:13
Yes, you're right. It's bug.

**Comment by qtxie** [comment] 2016-06-01 07:26
But if we set the `visible?` of the parent to `false`, all child windows become invisible too.

**Comment by qtxie** [comment] 2016-06-11 03:28
We can see the blue face now in the last version.

**Closed by qtxie** 2016-06-11 03:28 UTC
Labels: GUI, status.resolved, type.bug
