### ISSUE TITLE
[View] `event/key` is wrong for most numpad keys

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5170] opened 2022-08-02 18:41 UTC
**Describe the bug**

Side by side output from `on-key-down` and `on-key` (tested on W10 & GTK): 
```
num-lock num-lock    ;) Windows-only; GTK doesn't see the key at all
#"+" #"k"
#"-" #"m"
#"7" #"g"
#"8" #"h"
#"9" #"i"
#"4" #"d"
#"5" #"e"
#"6" #"f"
#"1" #"a"
#"2" #"b"
#"3" #"c"
#"0" #"`"
#"." #"n"
#"^M" #"^M"
none #"^S"
#"*" #"j"
#"/" #"o"
```

**To reproduce**

Run the following script:
```
view [
	box focus "press numpad keys"
	on-key [print [mold event/key mold key]]
	on-key-down [key: event/key]
]
```
Initial NumLock state: off (turned on then by first press)
Press keys: `NumLock + - 7 8 9 4 5 6 1 2 3 0 Del Enter Pause * /`

**Expected behavior**

1. Number keys instead of letters (period for del)
2. Pause key as `'pause` in both events, not as ctrl-s or none
3. NumLock (if possible) detected on GTK. 
4. CapsLock on GTK yields `none #"^T"` instead of `caps-lock caps-lock` right now. Should work as on Windows. Didn't test ScrollLock, might be messed up too.

**Platform version**
```
Red 0.6.4 for Windows built 27-Jun-2022/11:51:28+03:00  commit #ed73e33
Red 0.6.4 for Linux built 20-Jul-2022/7:20:15+03:00  commit #0897f65
```

**Comment by greggirwin** [comment] 2022-08-02 19:56
As always, thanks for the detailed report and tooling to help test.

**Comment by dockimbel** [comment] 2022-08-08 20:08
@qtxie I've taken care of the Windows part, I let you process the GTK part.

**Comment by qtxie** [comment] 2022-08-09 07:43
1. `event/key` is wrong in `on-key-down`, but it's correct in `on-key`, right? The title of the issue is not accurate.

2. For `on-key-down` and `on-key-up`, the value of `event/key` should be the same either `Num Lock` is on or off. I suggest that we always return number keys. That is, value of keys when `Num Lock` is on.

**Comment by hiiamboris** [comment] 2022-08-09 08:03
> For on-key-down and on-key-up, the value of event/key should be the same no matter Num Lock is on or off.

Currently, it's not the same. Why should it be? I think only `event/picked` (scancode) has to be the same.

**Comment by qtxie** [comment] 2022-08-09 08:22
> Currently, it's not the same. Why should it be? I think only event/picked (scancode) has to be the same.

To make it easier to know which key is pressed when you don't care much about the value of the key. No matter you pressed `Shift` or `Caps On`, the value is the same. Do we use `event/picked` for scancode?

**Comment by hiiamboris** [comment] 2022-08-09 08:36
Sorry I have misled you. I have no idea what `event/picked` is. Seems to return `to integer! event/key` for `char!` keys, but also some number for `word!` keys, but doesn't look like scan code.

**Comment by dockimbel** [comment] 2022-08-09 11:03
> Do we use event/picked for scancode?

Only if it can be a cross-platform value.

**Comment by dockimbel** [comment] 2022-08-09 13:42
> Scancodes are cross-platform by definition, however device-dependent :p
 
"cross-platform" includes both operating system and hardware.

**Comment by dockimbel** [comment] 2022-08-09 13:53
Damn auto-closing on "fixes" word!

**Comment by hiiamboris** [comment] 2022-08-10 09:34
Auto closed again ;)

**Closed** 2022-08-14 07:06 UTC
Labels: status.built, type.bug, status.reviewed, GUI, GUI.GTK

**Comment by dockimbel** [comment] 2022-08-14 21:32
@qtxie So, it's fixed for Windows too?

**Comment by dockimbel** [comment] 2022-08-14 21:33
@qtxie Thanks for fixing the Windows version too. 👍
