### ISSUE TITLE
[View] `size-text` not working with some fonts

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3727] opened 2019-01-14 06:11 UTC
**Describe the bug**

`size-text` returns 0x0 for all bitmap fonts (.fon) and opentype (.otf). As a result control (e.g. `field`) sizes cannot be automatically inferred.
![](https://i.gyazo.com/62b341a4c718cfef1cc748465a810651.png)
See also related https://github.com/red/red/issues/3726

**To reproduce**

[OpenType font "Rex Light" can be found on the web](https://fonts2u.com/rexlight.font)
Other fonts are bitmaps.
```
s: "123456789-123456789-123456789-"
f1: make font! [name: "Script" size: 14]
f2: make font! [name: "Rex Light" size: 14]
f3: make font! [name: "MS Serif" size: 14]
view compose/deep [
	backdrop purple below
	box purple 300x20 draw [font f1 text 0x0 (s)]
	box purple 300x20 draw [font f2 text 0x0 (s)]
	box purple 300x20 draw [font f3 text 0x0 (s)]
	box purple 300x20 font f1 s
	box purple 300x20 font f2 s
	box purple 300x20 font f3 s
	rich-text 300x20 purple font f1 s
	rich-text 300x20 purple font f2 s
	rich-text 300x20 purple font f3 s
	field font f1 s
	field font f2 s on-created [print size-text face]
	field font f3 s
]
```
Outputs: `0x0`

**Expected behavior**

Would be nice to have a full non-truetype font support.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 9-Jan-2019/5:46:16+03:00 commit #acf3492
W7
```

**Comment by bitbegin** [comment] 2019-07-30 07:58
Duplicate of #3760

**Comment by bitbegin** [comment] 2019-07-30 08:04
i can't found `script` and `MS Serif` font.
use the latest `Red` will show this:

![image](https://user-images.githubusercontent.com/4469745/62111693-bc6b9c00-b2e3-11e9-9d03-26f2e9cf5706.png)

**Comment by hiiamboris** [comment] 2020-03-04 16:00
Red 0.6.4 for Windows built 27-Feb-2020/6:07:00+03:00 commit #bf15211 on W7 with 125% scaling:
![](https://i.gyazo.com/9c0b160bdd55fa4ae3e91493267db167.png)

`print` outputs 1x1 rather than 0x0 now. `box` doesn't display these fonts anymore because it has been moved to GDI+ tech.

**Comment by dockimbel** [comment] 2022-09-28 21:46
Returns `306x21` now.

**Closed** 2022-09-28 21:46 UTC
Labels: status.built, status.tested, type.bug, GUI
