### ISSUE TITLE
resize issue A

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1644] opened 2016-02-17 18:39 UTC
In the following code, the `resize` button will resize `a` as expected, but resizing the window by dragging the edges or clicking the maximize button will not:

```
l: layout [a: area "Hello, World!" b: button "resize" [l/size: 100x100]]
react [a/size: l/size - 20]
view/flags l [resize]
```

Same on Windows XP and Windows 7.

**Comment by xqlab** [comment] 2016-02-19 08:53
Probably this is also the same reason, that the active window of the gui-console under wine does not resize.

**Comment by dockimbel** [comment] 2016-02-21 06:16
There's currently no resize event handler provided, that is why the above code does not work. I could add a special one for reactors processing. A fully automated resizing handler will be provided in a future version of Red/View.

I doubt the gui-console is affected by that as it uses its own resizing event handler.

**Comment by hiiamboris** [comment] 2019-05-10 19:16
Works for me on W7. Anyone can still reproduce the issue?

**Comment by greggirwin** [comment] 2019-05-11 03:31
Fine here on Win10. Closing the ticket.

**Closed by greggirwin** 2019-05-11 03:31 UTC
Labels: status.reviewed, type.review
