### ISSUE TITLE
Custom tab of the Tab-panel can't be selected on start

### ISSUE THREAD

**Issue by DVL333** [red/red#3838] opened 2019-04-06 00:41 UTC
**Describe the bug**
If set `selected` attribute for the tab-panel an appropriate tab won't be selected after creation

**To reproduce**
```
pnl1: make face! [type: 'panel]
pnl2: make face! [type: 'panel]
pnl3: make face! [type: 'panel]

repend tp: [] [pnl1 pnl2 pnl3]
tpnl: make face! [type: 'tab-panel size: 180x80 offset: 10x10 
    data: ["Tab1" "Tab2" "Tab3"] selected: 2 pane: tp]
repend p: [] [tpnl]

view make face! [type: 'window size: 200x120 pane: p]
```
**Expected behavior**
Proper tab must be selected on start (tab "Tab2" from the example)

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 25-Mar-2019/13:11:08+03:00 commit #e6c96aa
```

**Comment by 9214** [comment] 2019-04-06 10:24
May I humbly suggest to follow contribution guidelines and post *minimal* reproducible examples?

```red
view [tab-panel 150x50 data ["a" "b"] with [selected: 2]]
```

**Comment by dockimbel** [comment] 2019-04-18 20:55
This is a duplicate of ticket #2792. This is (surprisingly) a complex issue to solve on Windows. There is a [dedicated branch](https://github.com/red/red/tree/uni-tab-panel) that was started to redesign the way tab-panels are handled, but still unfinished.

**Comment by dockimbel** [comment] 2019-05-15 14:28
Closing this ticket, as it is a duplicate.

**Closed by dockimbel** 2019-05-15 14:28 UTC
Labels: status.duplicate
