### ISSUE TITLE
Area face does not scroll

### ISSUE THREAD

**Issue by meijeru** [red/red#1879] opened 2016-05-04 13:21 UTC
The documentation leads me to believe that text in an `area` face is scrolled if longer than the face can display (in any case if `wrap?` is set). However the following test program does not give scrolling:
```
Red [ ]
win: layout [long-text: area 200x100 wrap font-size: 36]
long-string: make string! 100
insert/dup long-string #"X" 100
long-text/text: long-string
view win
```

**Comment by dockimbel** [comment] 2016-05-05 04:04
The documentation says about `area`: *A vertical scroll-bar can appear if all lines of text cannot be visible in the area (might be controlled by a flags option in the future).* Is that what you are referring to?

**Comment by meijeru** [comment] 2016-05-05 08:11
Sorry for duplicating issues, but with the considerable number of tickets that are still on your plate, it is perhaps inevitable that we report issues without having checked thoroughly whether they have already been reported. As far as I am concerned you may as well close duplicates, so as to at least diminish the number of tickets that way...

**Comment by dockimbel** [comment] 2016-05-05 08:44
No worries, duplicates are a common thing in bugtracking systems despite the good will of reporters.

**Comment by dockimbel** [comment] 2016-05-06 11:01
I need to correct my comments above as I confused "scrolling" with "scrollbars". Your request and this ticket are legitimate and not duplicate of #1797.

**Closed** 2016-05-06 11:03 UTC
Labels: status.reviewed, type.bug
