### ISSUE TITLE
red-16feb15-d3a1ccb.exe crashed

### ISSUE THREAD

**Issue by bitbegin** [red/red#1038] opened 2015-02-18 03:15 UTC
log:
** Script Error: Not enough memory
** Near: script: decapsulate
if none? script

**Comment by qtxie** [comment] 2015-02-18 07:21
@bitbegin I can not reproduce it. It works well on my Win 7 64bit.

**Comment by bitbegin** [comment] 2015-02-18 11:00
My PC also is Win7 64bit. But there isn't more information.
How can I do to help you with this issue?

**Comment by qtxie** [comment] 2015-02-18 11:19
@bitbegin You would delete the old console in here: `"C:\ProgramData\Red\console.exe"`, then try again with administrator permission.

**Comment by dockimbel** [comment] 2015-02-25 02:39
@bitbegin I cannot reproduce it either. The only reason I could see about such error is a corrupted binary, that could result from a download issue or an anti-virus silently modifying the binary.

Can you reproduce that issue with newer binaries?

**Comment by bitbegin** [comment] 2015-02-25 11:26
@dockimbel  red-24feb15-3d15e1d.exe can be used normally. It was a download issue.

**Comment by dockimbel** [comment] 2015-02-25 15:23
Thank your for the reply. Closing this ticket now.

**Closed by dockimbel** 2015-02-25 15:23 UTC
Labels: Red, status.resolved
