### ISSUE TITLE
routine in nested context seems to return routine itself

### ISSUE THREAD

**Issue by koba-yu** [red/red#2405] opened 2017-01-06 15:20 UTC
I compile the code below and run.

```
outer-context: context [

    inner-context: context [

        get-one: routine [
            return: [integer!]
        ] [
            1
        ]
    ]

    get-add-one: function [return: [integer!]][
        temp: inner-context/get-one
        temp + 1 
    ]
]

outer-context/get-add-one
```
Then the error below is raised.

```
*** Script Error: + does not allow routine! for its value1 argument
*** Where: +
*** Stack: get-add-one +
```

According to error, I guess "get-one" routine returns routine itself  though defined return value is integer.

**Comment by PeterWAWood** [comment] 2017-01-07 02:22
I suspect the issue is due to the compiler not yet being able to recognise that get-one is a routine.

A workaround would be using:
```text
temp: do inner-context/get-one
```

**Comment by koba-yu** [comment] 2017-01-07 13:11
@PeterWAWood Thank you for your comment!
By your workaround, I could get my code progressed. I use it for the moment.

**Comment by dockimbel** [comment] 2017-02-14 14:25
Peter guessed right, the compiler is not yet able to handle relative paths for calling routines.

**Comment by dockimbel** [comment] 2017-10-10 10:49
The Red compiler has now better capabilities for resolving relative object paths, so the above code now runs fine and returns `2` as expected.

**Closed** 2017-10-10 10:49 UTC
Labels: status.built, status.tested, type.review
