### ISSUE TITLE
Access violation when executing a function in a context

### ISSUE THREAD

**Issue by Arie-vw** [red/red#3184] opened 2018-01-03 15:12 UTC
### Expected behavior
No crash

### Actual behavior
Access violation

### Steps to reproduce the problem
red --cli main.red
*** Runtime Error 1: access violation
*** at: 004341DEh

### Red version and build date, operating system with version.
OS: Windows 10 Pro X64 version 1709
Red for Windows version 0.6.3 built 3-Jan-2018/15:50:36+01:00 / red-03jan18-47d2a03.exe

[scripts.zip](https://github.com/red/red/files/1600736/scripts.zip)

**Comment by greggirwin** [comment] 2018-01-03 18:24
I haven't pulled your scripts Arie, but is it the same issue as https://github.com/red/red/issues/3156 ?

**Comment by Arie-vw** [comment] 2018-01-03 18:33
Hi Gregg,

maybe it is the same issue. Although it is also possible that it is related
to a load stmt in the function where it goes awry ...

Best regards,
   Arie

Op 3 jan. 2018 7:24 p.m. schreef "Gregg Irwin" <notifications@github.com>:

**Comment by greggirwin** [comment] 2018-01-03 18:38
Could you try to confirm, so we can close this ticket if it's a dupe? Thanks.

**Comment by rebolek** [comment] 2018-01-04 07:02
I can confirm it's the same bug, if you move everything into one file, it's basically same code as #3156.

**Comment by greggirwin** [comment] 2018-01-04 18:41
Thanks Bolek. Closing this ticket.

**Closed by greggirwin** 2018-01-04 18:41 UTC
