### ISSUE TITLE
dehex bug on the Mac 

### ISSUE THREAD

**Issue by rebred** [red/red#3780] opened 2019-02-13 21:34 UTC
**Describe the bug**
`dehex "%238710" ` gives the following error
```
*** Access Error: invalid UTF-8 encoding: #{E7262300}
*** Where: dehex
*** Stack:  
```
**To reproduce**
`dehex "%238710"`

**Expected behavior**

== "#8710"

**Screenshots**

**Platform version (please complete the following information)**
```
Red 0.6.4 for macOS built 4-Feb-2019/19:45:38+01:00 commit #a4d8240
```

**Comment by hiiamboris** [comment] 2019-02-14 00:18
Strangely, the same code is OK on W7 0.6.4 30-Jan-2019.

**Comment by greggirwin** [comment] 2019-02-14 07:34
I can't reproduce on Win10. This seems like it shouldn't be platform specific.

**Comment by PeterWAWood** [comment] 2019-02-14 09:03
In the cli-console: 

```text
>> about
Red 0.6.4 for macOS built 14-Feb-2019/16:55:25+08:00

>> dehex "%238710"
== "#8710"
```

In the gui-console:
```text
>> dehex "%238710"
== "#8710"
>> about
Red 0.6.4 for macOS built 14-Feb-2019/16:57:04+08:00
```

**Comment by 9214** [comment] 2019-02-14 10:03
`dehex` isn't platform-specific. Error mesage is caused by [this](https://github.com/red/red/blob/master/runtime/natives.reds#L1379) line. [Here](https://github.com/red/red/blob/master/runtime/datatypes/string.reds#L158) is `decode-utf8-hex` itself.

**Comment by rebred** [comment] 2019-02-14 20:28
`dehex "%9C%26%238721%3B%AE%B4%86%A9%F8%83%26%238706%3B%26%23729%3Bpdsjbkz"`

gives the following error
```
*** Access Error: invalid UTF-8 encoding: #{F8832623}
*** Where: dehex
*** Stack:  

```

**Comment by hiiamboris** [comment] 2019-02-14 20:50
Could be something to do with endianness? @rebred is your Mac OS on big-endian CPU?

**Comment by 9214** [comment] 2019-02-14 21:59
@rebred I can tell for sure that even online decoders have trouble with your input string, as it contains invalid Unicode characters, e.g. `U+F883`.

**Comment by 9214** [comment] 2019-03-12 10:55
> dehex "%9C%26 ...

Unless I'm missing something, `9C` is a continuation byte (starts with `10`) and cannot be the first byte of a code point.
```red
>> enbase/base #{9C} 2
== "10011100"
```

**Comment by dockimbel** [comment] 2019-09-10 23:04
Revelant definitions: https://en.wikipedia.org/wiki/Percent-encoding

**Comment by 9214** [comment] 2020-03-23 19:40
Cf. [RFC 3986](https://tools.ietf.org/html/rfc3986), a valid set of percent-encoded characters is:


! | # | $ | % | & | ' | ( | ) | * | + | , | / | : | ; | = | ? | @ | [ | ]
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
%21 | %23 | %24 | %25 | %26 | %27 | %28 | %29 | %2A | %2B | %2C | %2F | %3A | %3B | %3D | %3F | %40 | %5B | %5D

Thus:

In the [original](https://github.com/red/red/issues/3780#issue-410013226) report (which no one ever been able to reproduce):

| Part | Decoding |
|:-|:-|
| `%23 8710` | `#8710` |

Note the reported error message:

```red
*** Access Error: invalid UTF-8 encoding: #{E7262300}
*** Where: dehex
*** Stack:  
```
`E726` are trash bytes that precede `23` (`#` character), which is then followed by a null byte. That doesn't match the provided input. And if it does then the input is malformed and cannot be properly decoded.

In [subsequent](https://github.com/red/red/issues/3780#issuecomment-463782097) report:

| Part | Decoding |
|:-|:-|
| `%9C` | Trash byte |
| `%26%23 8721 %3B` | `&#8721;` |
| `%AE%B4%86%A9%F8%83` | Trash bytes |
| `%26%23 8706 %3B` | `&#8706;` |
| `%26%23 729 %3B` | `&#729;` |
| `pdsjbkz` | `pdsjbkz` |


Unless someone provides a reproducible example, I propose we close this.

**Comment by 9214** [comment] 2020-07-30 12:07
↑ ping.

**Comment by dockimbel** [comment] 2020-10-05 11:46
Closing as it can't be reproduced.

**Closed by dockimbel** 2020-10-05 11:46 UTC
Labels: status.dismissed
