### ISSUE TITLE
View: Window lost focus after a modal window close

### ISSUE THREAD

**Issue by endo64** [red/red#3942] opened 2019-07-23 14:13 UTC
**Describe the bug**
After closing a modal window the main window lost its focus and stays behind other windows.

Note that @toomasv [reported](https://gitter.im/red/bugs?at=5d3713ae5ea6e644ec063d18) that:
> build from May 21st, and there was no such problem.

**To reproduce**
```
view [button "Open Modal" 200 [view/flags [button 200 "Close Modal" [unview]] [modal] ] ]
```

**Expected behavior**
The window that opens the modal window should have focus after closing the modal.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 16-Jul-2019/18:28:15+03:00 commit #66ba8c8
```

**Comment by bitbegin** [comment] 2019-07-26 06:56
Duplicate of #3309

**Comment by bitbegin** [comment] 2019-07-27 10:18
still exist another issue, after `close modal`, the cmd shell will get focus (foreground) like this:

![lost](https://user-images.githubusercontent.com/4469745/61993207-f85ff080-b09a-11e9-81dc-ce2376d90ddc.gif)

**Comment by qtxie** [comment] 2019-07-27 17:32
Actually the "Open Modal" window is on the foreground, not the cmd shell. Looks like z-order of the cmd shell been promoted. As the cmd shell is for debugging purpose, if there is no easy fix, I'll let it as is for now.

**Comment by hiiamboris** [comment] 2020-01-29 21:18
Do this in GUI console: `view/flags [base] 'modal`  then close the modal window.
GUI console won't react to any key presses.

**Comment by greggirwin** [comment] 2020-01-30 01:29
Your test seems OK on Win10 @hiiamboris.

**Comment by hiiamboris** [comment] 2020-04-07 09:57
> 
> 
> Do this in GUI console: `view/flags [base] 'modal` then close the modal window.
> GUI console won't react to any key presses.

Also `alert "hi"` blocks the console after closing the window, as it's using `modal` flag.

**Closed** 2020-04-29 04:20 UTC
Labels: GUI, status.built, status.tested, type.bug
