### ISSUE TITLE
PRIN not showing output until newline

### ISSUE THREAD

**Issue by x8x** [red/red#1840] opened 2016-04-22 21:49 UTC
``` rebol
repeat n 10 [
    prin n
    wait 1
]
```

Above code will print `12345678910` after 10 seconds
instead of printing a number every second.

**Comment by x8x** [comment] 2016-04-23 04:34
@qtxie not sure if `GUI` label refers to GUI-console, the problem is everywhere, compiled and non compiled scripts, REPL and not, Linux and MacOS. Thank you!

**Comment by qtxie** [comment] 2016-04-24 00:29
It works fine in CLI console on Windows. I'll try Linux and MacOS later.

**Comment by nc-x** [comment] 2016-05-09 08:12
@qtxie Tested on Windows 8.1 GUI Console, got the same results as @x8x 
> Above code will print 12345678910 after 10 seconds
instead of printing a number every second.

On CLI console, I get the correct output as you got.

**Comment by BrianOtto** [comment] 2016-11-16 06:28
I am getting a similar issue when running the following example with red --cli on Windows 7.

`prin "Name: "
name: input
print ["Your name is" name]`

The "Name:" string is not displayed. However, if I add a newline to the string then it works, but this is not my desired behavior.

`prin "Name: ^/"`

**Comment by BrianOtto** [comment] 2016-11-18 07:21
Here is another example of prin not working correctly. I am trying to write some cross-platform CLI apps, and it's becoming very difficult to get things to display properly.

    prin "123"
    wait 5
    prin "456"

This works fine when running **red --cli** on Windows 7, but on Ubuntu 16.04.1 the "123" string doesn't display until after the 5 second wait is done.

**Comment by meijeru** [comment] 2016-11-18 07:47
Original example behaves wrongly on W10 as well.

**Comment by qtxie** [comment] 2016-11-18 11:55
@BrianOtto I pushed a fix for this issue, but using `input` still suppress the `prin`, needs more debug for it.
As a workaround, you can use `ask`:
```
name: ask "Name: "
print ["Your name is" name]
```

**Comment by x8x** [comment] 2016-11-18 18:24
@qtxie Thanks for this! Good to have `prin` working :-)
When you give a further look at prin/input, please also look if there is an easy fix for this https://github.com/red/red/issues/1845 .

**Comment by BrianOtto** [comment] 2016-11-18 22:34
@qtxie Awesome, thank you for fixing that so quickly!

I can confirm the original example provided by @x8x and my 2nd one works in Ubuntu 16.04.1 now.

Thank you for the workaround for my 1st example too. Using **ask** is working for me on Windows and Ubuntu :)

**Comment by dockimbel** [comment] 2017-02-16 11:18
It's still not working on the GUI console. It should be fixed definitely in 0.6.3 with the brand new GUI console engine.

**Comment by endo64** [comment] 2018-06-21 11:14
When `prin` followed by `input`, it does not output text, see [here](https://gitter.im/red/red/welcome?at=5b2b5d02ce3b0f268d347550),
When using `ask` instead of `input` it works, see [here](https://gitter.im/red/red/welcome?at=5b2b5fe1ad21887018d0ce4d),
This is interesting because `input` is simply calling `ask ""`.

**Comment by hiiamboris** [comment] 2018-06-21 12:05
@endo64 W7 x64 --cli:
```
>> prin "123" ask "4"
4_
>> prin "123" input
_
```
GUI:
```
>> prin "123" ask "4"
123
4_
>> prin "123" input
123
_
```
(`_` is to denote the caret position)

**Comment by qtxie** [comment] 2018-06-22 03:00
Needs to wait for full I/O to support it.

**Comment by greggirwin** [comment] 2019-03-20 16:42
See comment in #2627.

**Closed by greggirwin** 2019-03-20 16:42 UTC
Labels: status.reviewed, type.review

**Comment by hiiamboris** [comment] 2019-03-21 09:33
@greggirwin what about https://github.com/red/red/issues/1840#issuecomment-399067176 ?

**Comment by greggirwin** [comment] 2019-03-21 16:30
@Endo64 noted it was a duplicate of this one, and we could close this ticket.
