### ISSUE TITLE
Lexing inconsistency with set/get words starting with `<` character

### ISSUE THREAD

**Issue by Oldes** [red/red#4731] opened 2020-11-19 08:46 UTC
Currently:
```
>> quote <<<
== <<<
>> quote <<<:
*** Syntax Error: (line 1) invalid word at <<<:
```
which is also related to:
```
>> load {<<<}
== <<<
>> load {:<<<}
== [:< <<] ;<-- it should be `:<<<` instead as `<<<` is valid word now
```
```
Red 0.6.4 for Windows built 18-Nov-2020/3:13:59+01:00 commit #8ee5a9f
```

**Comment by 9214** [comment] 2020-11-19 08:47
Duplicate of https://github.com/red/red/issues/4562.

**Closed** 2020-11-19 08:49 UTC
