### ISSUE TITLE
bind 'self self doesn't work

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4501] opened 2020-06-05 14:56 UTC
**Describe the bug**

```
o: object [
    ? self
    ; x: bind 'self self       ;) this doesn't work either
    x: 'self
    ? x
    y: get x
    ? y
]
```
Output:
```
SELF is an object! with the following words and values:
     x  unset!        
     y  unset!        

X is a word! value: self

*** Script Error: self has no value
*** Where: get
*** Stack: object 
```

**Expected behavior**

Both `x: 'self` and `x: bind 'self self` should work

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 28-May-2020/17:51:04+03:00 commit #36857eb
```

**Comment by greggirwin** [comment] 2020-06-08 18:56
It does work in R2.
```
>> object: :context
>> do-clip
SELF is an object of value:
   x               unset!    none
   y               unset!    none

X is a word of value: self
Y is an object of value:
   x               word!     self
   y               object!   [x y]
```

**Comment by dockimbel** [comment] 2022-08-30 13:17
Let me dissipate a confusion: `self` in Red is not the same as in Rebol, especially R2. In R2 (not sure for R3), `self` is a first-class word in every object context (so it occupies a slot in the context table) as shown by this example:
```
>> probe first make object! [a: none]
[self a]
```
So that word can be manipulated as any word in general, using the different derivative word types.

In Red, `self` is a keyword that is part of an object construction dialect (along with the event handlers), it is not part of the object context (does not occupy any slot). It has meaning only when used only in `word!` form either standalone or as the first item of a path. So all the reported limitations above are by design.

In R2, `self` was often a burden, as it needed to be accounted for each time the object context was manipulated. Also ability to set it could caused weird effects and even crashes. In R3, IIRC, it's still takes a context slot, but it's more hidden to the user.

Given `self` limited purpose as its existence has meaning only inside an object's body, I think the current Red design fulfill its purpose properly, even if it requires some extra code and runtime overheads. Though, the discussion about its design is not set in stone in case we can come up with a better trade-off.

I'll close this ticket, the topic can be reopened as a REP or during the work on the language specs.

**Closed** 2022-08-30 13:21 UTC
Labels: status.dismissed, type.design

**Comment by greggirwin** [comment] 2022-08-30 19:45
Thanks for the explanation @dockimbel. :+1:
