### ISSUE TITLE
[macOS VID] RIGHT, LEFT, CENTER, BOTTOM, TOP, MIDDLE keywords do not work

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2735] opened 2017-06-02 09:24 UTC
```Red
view [ text 80x80 yellow right bottom "OK" ]
```

The problem only happens in macOS.

**Comment by hiiamboris** [comment] 2018-12-30 17:10
As of Dec 30, 2018 MacOS and Windows builds are consistent:
`view [ text 80x80 yellow right bottom "OK" ]` honors right/left but always displays text from the top (intended behavior or not?)
`view [ base 80x80 yellow right bottom "OK" ]` honors vertical alignment as well.

**Comment by qtxie** [comment] 2019-01-04 01:18
@hiiamboris The `text` face does not support all the alignments, it's a limitation of the native control.

**Comment by hiiamboris** [comment] 2019-01-04 02:14
Hmm. Theoretically we could still emulate that, but I believe it's not worth the trouble, as base already supports all that. Then as everything that was fixable was fixed, this issue can be closed?

**Comment by greggirwin** [comment] 2019-01-05 01:41
I'll close this, and ask @gltewalt to note the limitation in docs.

**Closed** 2019-01-05 02:07 UTC
Labels: GUI, status.reviewed, type.review
