### ISSUE TITLE
Crash when assign function result of an object

### ISSUE THREAD

**Issue by Zamlox** [red/red#3202] opened 2018-01-16 11:22 UTC
### Expected behavior
Following sequence of code should execute in gui console without crashing
```
a: none
obj: object [
	f1: does [
		11
	]
]
a: obj/f1
```
### Actual behavior
It crash when executed in gui console
Culprit commit: bca86785936b0750b994702daa15734361237f1f
### Steps to reproduce the problem
Fire up gui console and execute the above code
### Red version and build date, operating system with version.
Red for Windows version 0.6.3 built 16-Jan-2018/9:28:40+02:00
OS: Windows 7

**Comment by rebolek** [comment] 2018-01-16 12:13
This is duplicate of https://github.com/red/red/issues/3156

**Comment by Zamlox** [comment] 2018-01-16 12:15
Yep, looks like.

**Comment by greggirwin** [comment] 2018-01-16 18:03
Added a comment for this ticket to #3156, and will close this so we focus there.

Thanks @zamlox!

**Closed by greggirwin** 2018-01-16 18:03 UTC

**Comment by toomasv** [comment] 2018-01-20 19:49
As with sibling issues, explicit typing is work-around:
```
>> a: to-integer obj/f1
== 11
```

**Comment by gltewalt** [comment] 2018-01-21 00:31
>> a: reduce obj/f1
== 11
