### ISSUE TITLE
Content obscures title in group box

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#1871] opened 2016-05-02 00:23 UTC
Titles in a `group-box` are obscured by the content.

This code:

``` Red
Red [
    Needs: 'View
]

view [
    title "My Layout"
    group-box 2 [
        title "Heading" 
        text "Field 1" right
        field 200 
        text "Much Longer Field Name" right
        field 200
    ]
]
```

Produces this output:
<img width="394" alt="group box with title" src="https://cloud.githubusercontent.com/assets/697434/14945226/19ea50a6-103f-11e6-821b-0d2e2cb69b2f.png">

**Comment by dockimbel** [comment] 2016-06-17 16:48
We'll add support for proper internal padding with appropriate default values in a future release.

**Comment by hiiamboris** [comment] 2018-12-30 17:30
Is this still not fixed? Can't reproduce on W7 and W8.

**Comment by endo64** [comment] 2019-01-01 19:40
`Heading` text looks ok but no padding, here is how it looks on W10 with latest build (`Red 0.6.4 for Windows built 1-Jan-2019/17:22:21+03:00 commit #8bf2cbe`)

![image](https://user-images.githubusercontent.com/840604/50575805-0526a980-0e16-11e9-99ff-4fdc23a523fe.png)

**Comment by greggirwin** [comment] 2019-01-02 23:21
Still has the issue for the second label.

**Comment by hiiamboris** [comment] 2020-07-17 16:08
I propose we close this as "Heading" is not clipped anymore, and 2nd field has it's width set explicitly to `200`, so expected to be clipped.

**Closed** 2020-07-17 18:00 UTC
Labels: GUI, status.reviewed, type.review
