### ISSUE TITLE
I installed Red (2021-sept-30) and it cannot run from console on Win10 x64

### ISSUE THREAD

**Issue by Alexey-T** [red/red#4976] opened 2021-10-01 09:32 UTC
Installed to c:\Red\red.exe, it created the console exe.

If I run c:\red\red.exe - it runs ok.
If I add c:\Red to system PATH and run "red" from terminal - it gives error
```
C:\Users\user>red
PROGRAM ERROR: Invalid encapsulated data.
```

**Comment by hiiamboris** [comment] 2021-10-01 10:06
dupe of https://github.com/red/red/issues/543

**Closed** 2021-10-01 10:07 UTC
Labels: status.duplicate

**Comment by qtxie** [comment] 2021-10-01 10:16
You need the CLI version of the console when communicating with editor.

> red --cli
