### ISSUE TITLE
Contributing to the project from macOS Catalina

### ISSUE THREAD

**Issue by drkameleon** [red/red#4652] opened 2020-09-19 10:04 UTC
I'm a huge fan of Rebol and Red and as a matter of fact I am the creator of a programming language inspired by it (written in C & Nim).

I'm also willing to contribute to Red.

The problem is Red depends on the Rebol2 binary and Rebol2 in practically unrunnable on Catalina. (I use them both via Docker, but cannot be the way to go)

Any ideas on how I could solve the issue?

**Comment by hiiamboris** [comment] 2020-09-19 16:39
Hi @drkameleon ;)
Please use the [official Gitter chat](https://gitter.im/red/red) for questions ;)

Re: 64 bits. This is a well known limitation and [here is the team's stance on it](https://gitter.im/red/red?at=5e09152cd5a7f357e6a1af83). In the mean time there were [attempts to dockerize Red for Catalina users](https://github.com/rcqls/red-gtk-macOS), but you may want to ask around Gitter for an up to date info. @x8x and @rcqls may know more.

I'm closing this issue as a dupe of https://github.com/red/red/issues/4359

**Closed by hiiamboris** 2020-09-19 16:39 UTC

**Comment by vazub** [comment] 2020-09-21 14:30
@drkameleon Here is the solution I am using, scratching the very same itch:
https://gitlab.com/vazub/rebol2-docker
https://gitlab.com/vazub/red-docker

**Comment by rozek** [comment] 2023-08-01 13:03
> @drkameleon Here is the solution I am using, scratching the very same itch: https://gitlab.com/vazub/rebol2-docker https://gitlab.com/vazub/red-docker

Dockerfile and instructions do not seem to work any more (e.g., there is no "red-latest" any more) For that reason, I've made my own Docker image (as described [here](https://github.com/rozek/docker-red)) and figured out how to run RED/Rebol CLI/GUI scripts under macOS Ventura on "Mac Silicon"

The Dockerfile should also be useful for Windows and Linux users - but the commands to start GUI scripts may certainly differ...

**Comment by greggirwin** [comment] 2023-08-01 17:22
Thanks for diving into this @rozek.
