### ISSUE TITLE
DOC: insert into string does an implicit FORM 

### ISSUE THREAD

**Issue by meijeru** [red/red#2423] opened 2017-01-26 18:00 UTC
AFAIK this is undocumented. But I suppose the feature is intentional... It is present in R2/3 also.

**Comment by greggirwin** [comment] 2017-01-27 20:35
I believe it is by design.

**Comment by meijeru** [comment] 2017-01-28 14:50
Reason the more to document it. The docstring is now:
```
Inserts value(s) at series index; returns series past the insertion. 
```
I would add: `If series is string!, the value is FORMed`

**Comment by greggirwin** [comment] 2017-01-28 16:08
That will make the doc string much longer, without added benefit IMO. That is, what other *possible* behavior could there be? Only `mold`. If the change is made, `append` and `change` should probably be updated to match.

**Comment by meijeru** [comment] 2017-01-28 16:40
It is not so trivial, since in R2 `insert #{ } 3` gives `#{33}` and in R3 it gives `#{ 03}`. Thus, `insert "" 3` might well give "^(03)". In other words, any implicit conversions should preferably be flagged

**Comment by greggirwin** [comment] 2017-01-28 20:24
Inserting into a binary! is very different from inserting into a string. And of course there is no round trip, because you always get a char! when you pick from a string. I understand what you mean though.

You make a good point with integers, but the same applies to tuples and other values. Assuming we agree that the implicit `form` behavior is the best choice, the doc string is the question. I believe the target length for doc strings is 70 chars or less, though some will surely be longer. The current doc string is 68 chars. Adding your extra text would make it 110. We should actually use slightly different added text, because it applies to `any-string!` types, not just `string!`.

As soon as we say any implicit conversions should be noted in doc strings, I think things are going to explode, and perhaps be even more confusing. For example, if you insert a tuple! into a binary!, is it implied that the dots separating the segments, which are part of the lexical form, are excluded?

Doc strings, by nature of needing to be brief, will sometimes be vague. Extended docs, elsewhere, can note detailed behaviors.

**Comment by geekyi** [comment] 2017-02-03 11:54
Agree with @greggirwin here. But from a different point of view:
*Noting that `insert/only` is already taken for something else. But assume it's not; for argument's sake*

If instead of changing the docstring, if there was a `/only` refinement which doesn't do any conversion, would it be better for you @meijeru?

**Comment by meijeru** [comment] 2017-02-03 12:23
I can live with a properly documented behaviour. I do not see a use for prohibiting the conversion with a refinement.

**Comment by dockimbel** [comment] 2017-02-12 11:07
@geekyi When you insert a non-string value in a string, you *must* convert that value to a string, so a conversion rule is required. The conversion function used by `insert` is FORM.

**Comment by dockimbel** [comment] 2017-02-12 11:11
Doc-string are not meant to provide an exhaustive description, just a short reminder of the purpose of the function. Such more in-depth explanation should IMHO have its place in a Red dictionary page (which the user could somehow access from the Red console).

**Comment by dockimbel** [comment] 2019-09-11 15:49
I will close this issue, as there is no official documentation for the Red Language, so it's pointless for now to report features to be documented in red/red as issues (unless the description is for the docstring specifically).

**Closed** 2019-09-11 15:49 UTC
Labels: status.deferred, type.review
