### ISSUE TITLE
Wrong compiler error, when compiling bad REPEAT code

### ISSUE THREAD

**Issue by rebolek** [red/red#2235] opened 2016-09-21 08:46 UTC
This is related to #1831 that is fixed for interpreter. Compiler throws compile error, which is fine, but the error description is confusing.

Code:

```
Red []

function [a] [repeat a/1]
```

Compiler output:

```
Compiling E:\Code\red-bugs\test.red ...
*** Compilation Error: invalid function spec block: [1]
*** in file: %/E/Code/red-bugs/test.red
*** near: [[a
        /local a 1
    ] [repeat a/1]]
```

As you can see, `1` is taken as local argument, which is not true.

**Comment by dockimbel** [comment] 2017-02-17 15:55
Duplicate of #2194

**Closed** 2017-02-17 15:55 UTC
Labels: status.duplicate
