### ISSUE TITLE
Accepts powers of wrong type

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1354] opened 2015-09-16 12:05 UTC
```
red>> 0 ** "death"
== 0
red>> 1 ** "death"
== 1
red>> 2 ** "death"
== 0
red>> 3 ** "death"
== -1971559983
red>> 4 ** "death"
== 0
red>> 5 ** "death"
== -1103539215
red>> 6 ** "death"
== 0
red>> 7 ** "death"
== 1633022561
red>> 8 ** "death"
== 0
red>> 9 ** "death"
== 1792007841
```

**Comment by qtxie** [comment] 2015-09-17 01:49
It's caused by no type checking for op! in the interpreter.

**Comment by dockimbel** [comment] 2016-02-06 17:45
Fixed by commit [94e002b1](https://github.com/red/red/commit/b20d3c6147d81724c45c96753671fd2f94e002b1).

**Closed** 2016-02-06 17:45 UTC
Labels: Red, status.built, status.tested, type.bug

**Comment by rebolek** [comment] 2016-09-02 14:55
Still returns 0 instead of error!  when compiled.

**Comment by rebolek** [comment] 2016-09-20 15:51
Also in interpreter:

```
--== Red 0.6.1 ==-- 
Type HELP for starting information. 

red>> 0 ** "death"
== 0
red>> 
```
