### ISSUE TITLE
[View] `do-events` isn't considering the absence of windows

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3682] opened 2018-12-26 16:30 UTC
**Describe the bug**
When no windows are open:
```
>> do-events
*** Script Error: path none is not valid for none! type
*** Where: eval-path
*** Stack: do-events
```
Moreover, the same happens when a window was *just* closed: it is still inside a pane, but it's `state` is already `none`.

**Expected behavior**
It should check for both empty screen `pane` and `none? state` and exit silently.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 18-Dec-2018/23:37:37+03:00 commit #873a756
```

**Comment by dockimbel** [comment] 2018-12-29 09:15
> When no windows are open:

Do I understand implicitly that you are running the code from the CLI console?

**Comment by hiiamboris** [comment] 2018-12-29 12:34
@dockimbel you're correct, I'm using the CLI console. Should've been clear on that.
On Windows it is defined there if you run `red --cli`. It is also defined when you compile it with `needs: view`. Although it is indeed undefined if compiled without.

**Comment by dockimbel** [comment] 2019-09-07 14:44
@hiiamboris How do I reproduce the "when a window was just closed" case? I tried without success:
```
>> view [] do-events
== none
```

**Comment by dockimbel** [comment] 2019-09-07 15:13
I applied a blind patch as I can't reproduce the "window just closed" case. As the main issue reported has been fixed by endo, I'll close this ticket.

**Closed** 2019-09-07 15:14 UTC
Labels: status.built, status.tested, type.review

**Comment by hiiamboris** [comment] 2020-03-06 19:48
For the record, I couldn't reproduce "window just closed" case in the current builds (and it was never trivial to begin with), but I suppose it was due to premature faces destruction as happens in https://github.com/red/red/issues/4319
