### ISSUE TITLE
<anon> instead of value2 in errors for logic operators

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1353] opened 2015-09-16 12:03 UTC
In the errors for `and`, `or` and `xor`, it says `<anon> argument` instead of `value2 argument`.

```
red>> none and true
*** Script error: and does not allow none for its value1 argument
*** Where: and
red>> true and none
*** Script error: and does not allow none for its <anon> argument
*** Where: and
```
```
red>> none or true
*** Script error: or does not allow none for its value1 argument
*** Where: or
red>> true or none
*** Script error: or does not allow none for its <anon> argument
*** Where: or
```
```
red>> none xor true
*** Script error: xor does not allow none for its value1 argument
*** Where: xor
red>> true xor none
*** Script error: xor does not allow none for its <anon> argument
*** Where: xor
```

The errors for `and~`, `or~` and `xor~` do say `value2 argument` where appropriate.

**Comment by qtxie** [comment] 2015-09-17 01:48
It's caused by no type checking for op!.

**Comment by WiseGenius** [comment] 2016-02-06 18:35
This is now working as expected.

**Comment by dockimbel** [comment] 2016-02-06 18:37
Fixed by commit [94e002b1](https://github.com/red/red/commit/b20d3c6147d81724c45c96753671fd2f94e002b1).

**Comment by x8x** [comment] 2016-08-09 04:49
Not sure what the issue is here, if it's about errors returning `<anon>`, then I'm still getting same results as above.

**Comment by WiseGenius** [comment] 2016-08-09 12:11
So am I. It must have had a relapse.

**Closed** 2016-08-09 14:22 UTC
Labels: status.built, status.tested, type.review
