### ISSUE TITLE
Load 1. as float! value

### ISSUE THREAD

**Issue by jeffmaner** [red/red#2172] opened 2016-08-12 20:04 UTC
Rebol loaded `1.` as a `decimal!` value. Red complains that `1.` is an invalid `integer!`. It'd be cool if Red were to load `1.` as a `float!`. Thanks!

**Comment by meijeru** [comment] 2016-08-12 21:57
Duplicate of #1642

**Comment by qtxie** [comment] 2016-08-13 01:15
Close it as it's a duplicate issue.

**Closed by qtxie** 2016-08-13 01:15 UTC
