### ISSUE TITLE
Avira Blocked and quarantined Red programdata

### ISSUE THREAD

**Issue by singam96** [red/red#2903] opened 2017-07-19 19:13 UTC
https://files.gitter.im/red/red/1Rz3/image.png

**Comment by dockimbel** [comment] 2017-07-20 03:17
Thanks, though it's a duplicate of #2399. Avira is the last big AV which is causing us trouble, and their support service is really bad.

**Comment by singam96** [comment] 2017-07-20 07:20
ooh my bad.

**Comment by dockimbel** [comment] 2017-07-23 08:10
@singam96 Could you provide us with the version/build/date of your Avira signatures databases and engine?

**Comment by singam96** [comment] 2017-07-23 09:20
this is the link
https://files.gitter.im/red/red/vQiB/image.png

**Closed** 2020-03-22 22:19 UTC
Labels: type.AV
