### ISSUE TITLE
Extremely slow `help` output on bigger data

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5301] opened 2023-04-01 16:43 UTC
**Describe the bug**

```
>> system/console/size
== 93x46

>> append/dup b: [] pi 100000
== [3.141592653589793 3.141592653589793 3.141592653589793 3.141592653589793 3.14159265358...

>> clock [mold/part b system/console/size/x]
0.0 μs  [mold/part b system/console/size/x]
== {[3.141592653589793 3.141592653589793 3.141592653589793 3.141592653589793 3.1415926535...

>> clock/times [mold/part b system/console/size/x] 1e5
19.7 μs [mold/part b system/console/size/x]
== {[3.141592653589793 3.141592653589793 3.141592653589793 3.141592653589793 3.1415926535...

>> clock [? b]
B is a block! value.  length: 100000  [3.141592653589793 3.141592653589793 3.141592653589...

347 ms  [? b]
```
That's 17600x slowdown compared to `mold`.

**To reproduce**
```
system/console/size
append/dup b: [] pi 100000
clock [mold/part b system/console/size/x]
clock [? b]
```

**Expected behavior**

Reasonable output time.

**Platform version**
```
-----------RED & PLATFORM VERSION----------- 
RED: [ branch: "master" tag: #v0.6.4 ahead: 4629 date: 28-Jan-2023/11:28:13 commit: #ec0c31279023590e285fb2e1869380670ee0239f ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 19044 ]
--------------------------------------------
```

**Comment by greggirwin** [comment] 2023-04-01 18:35
The crux of the matter being that `mold` is slow on large data, and we should use `mold/part` based on console width? I had to dig in to be sure it wasn't something else in `help`, but that looks like it.

**Comment by greggirwin** [comment] 2023-04-01 18:37
The issue is that the outer part of formatting catches it, but block formatting has an inner part for the block contents that doesn't.

**Comment by dockimbel** [comment] 2023-04-01 18:41
```
>> clock [help-ctx/form-value b]
124 ms	[help-ctx/form-value b]
```

**Comment by greggirwin** [comment] 2023-04-01 18:44
Fix is in, but there's another line change from old func-attr change some time back. :^\

**Comment by greggirwin** [comment] 2023-04-01 18:49
Looks like that was never PR'd. :^\

**Comment by greggirwin** [comment] 2023-04-01 18:51
Nvm. It was and I am out of sync here.

**Comment by greggirwin** [comment] 2023-04-01 18:57
https://github.com/red/red/pull/5302

**Closed** 2023-04-01 18:58 UTC
Labels: type.bug

**Comment by greggirwin** [comment] 2023-04-01 18:59
After the fix:
```
0.0 μs	[mold/part b system/console/size/x]
B is a block! value.  length: 100000  [3.141592653589793 3.141592653589793 3.141592653589793 3.141592653589793 3.141592653589793 ...

6.97 ms	[? b]
```
