### ISSUE TITLE
Wish: escaping support for op!

### ISSUE THREAD

**Issue by nickkoro02** [red/red#3250] opened 2018-03-09 16:24 UTC
### Wished behavior
```Red
>> add-and-assign: function ['word value] [print [word value] set word add get word value]
>> i: 0
>>
>> add-and-assign i 3
i 3
== 3
>>
>> +=: make op! :add-and-assign
>>
>> i += 1
i 1
== 4
```
### Actual behavior
```Red
>> i += 1
3 1
*** Script Error: set does not allow integer! for its word argument
*** Where: set
*** Stack:

```
### Steps to reproduce the problem
See above.

### Red version and build date, operating system with version.
```
Red for Windows version 0.6.3 built 12-Aug-2017/21:38:44+02:00
Windows 10 x64
```

**Comment by dockimbel** [comment] 2018-03-09 17:08
I think there is already a ticket asking for literal argument support for user-defined infix function.

**Comment by 9214** [comment] 2018-03-09 17:16
https://github.com/red/red/issues/3179

**Comment by greggirwin** [comment] 2018-03-09 17:29
Closing as a duplicate of #3179, but also linked to this ticket from there.

**Closed by greggirwin** 2018-03-09 17:29 UTC
Labels: type.wish
